#pragma once 

enum AOState : U8
{
	STATE_AGENT_IDLE,
	STATE_AGENT_WALK,
	STATE_AGENT_RUN,

	STATE_AGENT_PRE_JUMP,
	STATE_AGENT_JUMP,
	STATE_AGENT_TURNLEFT,
	STATE_AGENT_TURNRIGHT,

	STATE_AGENT_SIT,
	STATE_AGENT_SIT_GROUND,

	STATE_AGENT_HOVER,
	STATE_AGENT_HOVER_DOWN,
	STATE_AGENT_HOVER_UP,

	STATE_AGENT_CROUCH,
	STATE_AGENT_CROUCHWALK,
	STATE_AGENT_FALLDOWN,
	STATE_AGENT_STANDUP,
	STATE_AGENT_LAND,

	STATE_AGENT_FLY,
	STATE_AGENT_FLYSLOW,

	STATE_AGENT_TYPE,

	STATE_AGENT_SWIM_DOWN,
	STATE_AGENT_SWIM_UP,
	STATE_AGENT_SWIM,
	STATE_AGENT_FLOAT,
	STATE_AGENT_END
};
