# This is a basic workflow to help you get started with Actions

name: genesis-deploy-release

on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  PROJECT_ID: ${{ secrets.GCE_PROJECT }}
  GCE_INSTANCE: windows-genesis-build-template-202206  # TODO: update to instance name
  GCE_INSTANCE_ZONE: us-central1-a   # TODO: update to instance zone
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  create-runner:
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.create-runner.outputs.label }}
    steps:
      - id: create-runner
        uses: MelyCosti/gcp-runner@main
        with:
          project_id: ${{ secrets.GCE_PROJECT }}
          service_account_key: ${{ secrets.GCE_SA_KEY }}
          machine_zone: us-central1-a
          machine_type: n1-standard-4
          actions_preinstalled: true
          token: ${{ secrets.GH_SA_TOKEN }}

  git_checkout :
    needs: create-runner
    runs-on: ${{ needs.create-runner.outputs.label }}
    steps:
     - id: git_checkout
       uses: actions/checkout@v3
       with:
          ref: ${{env.GITHUB_REF}}
          fetch-depth: 0
  
  destroy_runner:
    needs: create-runner
    runs-on: ${{ needs.create-runner.outputs.label }}
    steps:
      - run: echo "This runs on the GCE VM"
      - uses: MelyCosti/gcp-runner@main
        with:
          command: stop
        if: always()
