# This is a basic workflow to help you get started with Actions

name: test-genesis-release

on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  download-artefacts :
    
    runs-on: ubuntu-latest
    steps:
      
      - name: downloading-private-fmod
        
        env:
         dep_pass: ${{ secrets.DEP_PASS}}
         dep_user: ${{secrets.DEP_USER}}
        run: mkdir -p /tmp/deps/ && curl -u ${dep_user}:${dep_pass} https://londoncitysl.com/genesis/dependencies/private/fmodstudio-2.00.03-windows64-192401637.tar.bz2 --output /tmp/deps/fmodstudio-2.00.03-windows64-192401637.tar.bz2
      - uses: actions/upload-artifact@v2
        with:
          name: fmod
          path: /tmp/deps/
  build :
    needs: [download-artefacts]
    runs-on: windows-latest
    steps:
     
     
     - id: install-autobuild
       uses: actions/setup-python@v4
       with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
     - run : pip install git+https://bitbucket.org/lindenlab/autobuild.git@v3    
     
     - name: downloading-private-fmod
       uses: actions/download-artifact@v2
       with:
           name: fmod
           path: c:/temp/
     
     - uses: geekyeggo/delete-artifact@v1
       with:
          name: fmod
     - name: ls
       run: ls -l c:/temp/
     - name: Add msbuild to PATH
       uses: microsoft/setup-msbuild@v1.1
       with:
         msbuild-architecture: x64
    
         
     - id: code-checkout
       uses: actions/checkout@v3
       with:
          ref: ${{env.GITHUB_REF}}
          fetch-depth: 0
     - id: autobuild-configure
       run : echo 'set AUTOBUILD_WIN_VSHOST=v143  && autobuild configure -cRelease -A64 -- -DUSE_FMODSTUDIO:BOOL=ON'>configure.cmd
     - id: run-autobuild-configure  
       run : ./configure.cmd
     - id: build-setup
       run : autobuild build --no-configure -cRelease -A64
  
  
