name: test-rename-setup

on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build :

      runs-on: windows-latest
      steps:
        - name: create a fake directory
          run : mkdir ./build-vc-64 && mkdir ./build-vc-64/newview && mkdir ./build-vc-64/newview/Release
        - name: create fake Setup
          run : echo "Test" > ./build-vc-64/newview/Release/Genesis-Eve_0_0_1_52_x86_64_Setup.exe
        - name: find and rename
          run : Get-ChildItem .\build-vc-64\newview\Release\*Setup.exe | Rename-Item -NewName "Genesis-eve-0.0.1_nightly_build_$(get-date -f yyyy-MM-dd).exe" && mv ".\build-vc-64\newview\Release\Genesis-eve-0.0.1_nightly_build_$(get-date -f yyyy-MM-dd).exe" c:/temp/
        - name: ls
          run : ls -l c:/temp/
        - name: store artefact
          uses: actions/upload-artifact@v2
          with:
            name: Genesis-setup
            path: c:/temp/Genesis*
            
  upload:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: create a tmp dir
        run: mkdir -p ./Genesis
      - name: download artefact
        uses: actions/download-artifact@v2
        with:
          name: Genesis-setup
          path: ./Genesis/
      - name: ls
        run: ls -l ./Genesis/
      - name: Upload from Genesis via FTP
        uses: airvzxf/ftp-deployment-action@latest
        with:
          server: ${{ secrets.FTP_HOST }}
          user: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          local_dir: "./Genesis"
          remote_dir: "/genesis/nightly_builds"
          delete: "false"
          max_retries: "7"
          no_symlinks: "false"
          ftp_ssl_allow: "true"
          ftp_use_feat: "true"
          ftp_nop_interval: "9"
          net_max_retries: "0"
          net_persist_retries: "11"
          net_timeout: "13s"
          dns_max_retries: "17"
          dns_fatal_timeout: "never"
      
