name: test-download-artefact
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  
  build :
    
    runs-on: ubuntu-latest
    steps:
      
      - name: downloading-private-fmod
        
        env:
         dep_pass: ${{ secrets.DEP_PASS}}
         dep_user: ${{secrets.DEP_USER}}
        run: curl -u ${dep_pass}:${dep_user} https://londoncitysl.com/genesis/dependencies/private/fmodstudio-2.00.03-windows64-192401637.tar.bz2 --output /temp/fmod.tar.bz2
                
