# This is a basic workflow to help you get started with Actions

name: test-genesis-release

on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  build :
    
    runs-on: windows-latest
    steps:
     
     
     - id: install-autobuild
       uses: actions/setup-python@v4
       with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
     - run : pip install git+https://bitbucket.org/lindenlab/autobuild.git@v3    
     - id: install-wget
       uses: actions/setup-python@v4
       with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
     - run : pip install wget
     - name: downloading-private-fmod
       run: python -m wget  -O c:/temp/fmodstudio-2.00.03-windows64-192401637.tar.bz2 https://${{secrets.DEP_USER}}:${{ secrets.DEP_PASS}}@londoncitysl.com/genesis/dependencies/private/fmodstudio-2.00.03-windows64-192401637.tar.bz2
       
     - name: Add msbuild to PATH
       uses: microsoft/setup-msbuild@v1.1
       with:
         msbuild-architecture: x64
     
     - id: autobuild-configure
       run : echo 'set AUTOBUILD_WIN_VSHOST=v143  && autobuild configure -cRelease -A64 -- -DUSE_FMODSTUDIO:BOOL=ON'>configure.cmd
     - id: run-autobuild-configure  
       run : ./configure.cmd
     - id: build-setup
       run : autobuild build --no-configure -cRelease -A64
  
  
