# This is a basic workflow to help you get started with Actions

name: test-ftp

on:
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  upload-artefacts :
    
    runs-on: ubuntu-latest
    steps:
      - name: maketestfile
        run: mkdir -p /tmp/test/ && echo "test" > /tmp/test/test.ok2
      - name: upload  
        run: git ftp push -u ${{ secrets.FTP_USER }} -p ${{ secrets.FTP_PASS }} --syncroot /tmp/test/ ftp://${{ secrets.FTP_HOST }}/genesis/
