name: test-download-artefact
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  
  download-artefacts :
    
    runs-on: windows-latest
    steps:
      
      - name: downloading-private-fmod
        
        env:
         dep_pass: ${{ secrets.DEP_PASS}}
         dep_user: ${{secrets.DEP_USER}}
        run: curl -u ${dep_user}:${dep_pass} https://londoncitysl.com/genesis/dependencies/private/fmodstudio-2.00.03-windows64-192401637.tar.bz2 --output /tmp/fmod.tar.bz2
      - name: Cache Deps
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: /tmp/fmod.tar.bz2
          key: fmod
          
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache Deps
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: c:\temp\fmod.tar.bz2
          key: fmod

      - name: ls
        
        run: dir c:/temp/
